controller_manager:
  ros__parameters:
    update_rate: 100 # Hz

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    forward_velocity_controller:
      type: controller_new/ForwardVelocityController

joint_state_broadcaster:
  ros__parameters: {}

forward_velocity_controller:
  ros__parameters:
    joint: "wheel_joint"