<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="rrbot">


  <xacro:property name="base_link_x" value="0.1" />
  <xacro:property name="base_link_y" value="0.1" />
  <xacro:property name="base_link_z" value="0.1" />

  <xacro:property name="link1_length" value="1.0" />
  <xacro:property name="link1_radius" value="0.05" />
  <xacro:property name="link2_length" value="1.0" />
  <xacro:property name="link2_radius" value="0.05" />

  <link name="base_link">
    <visual>
      <geometry>
        <box size="${base_link_x} ${base_link_y} ${base_link_z}"/>
      </geometry>
      <material name="grey">
        <color rgba="0.5 0.5 0.5 1.0"/>
      </material>
    </visual>
  </link>

  <link name="link1">
    <visual>
      <geometry>
        <cylinder length="${link1_length}" radius="${link1_radius}"/>
      </geometry>
      <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0"/>
      <material name="blue">
        <color rgba="0.1 0.6 0.5 1.0"/>
      </material>
    </visual>
  </link>

  <link name="link2">
    <visual>
      <geometry>
        <cylinder length="${link2_length}" radius="${link2_radius}"/>
      </geometry>
      <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0"/>
      <material name="green">
        <color rgba="0.2 0. 0.6 1.0"/>
      </material>
    </visual>
  </link>

  <joint name="joint1" type="continuous">
    <parent link="base_link"/>
    <child link="link1"/>
    <origin xyz="0 0 ${base_link_z / 2}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
  </joint>

  <joint name="joint2" type="continuous">
    <parent link="link1"/>
    <child link="link2"/>
    <origin xyz="0 0 ${link1_length}" rpy="0 0 0"/>
    <axis xyz="1 0 0"/>
  </joint>


</robot>